sudo: false
language: node_js
node_js: 7
install:
  - npm install '@angular/cli' -g
  - npm install
  - gem install compass
script:
  - node --version
  - ng version
  - SCRIPTS_FN=src/environments/environment.prod.ts
  - sed "s/WENFO_GOOGLE_MAPS_API_KEY/$GOOGLE_MAPS_API_KEY/g" < $SCRIPTS_FN > tmp
  - mv tmp $SCRIPTS_FN
  - npm run build
deploy:
  # deploy to "wenfo.org/afms" (Aus. Flammability Monitoring System)
  skip_cleanup: true
  provider: script
  script: bash -c "cd dist && find . -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp.wenfo.org{} \;"
  on:
      branch: master
notifications:
  email: false
  slack:
    rooms: wenfo:N1YfzQWaJ8wfjvrYarrh33PZ
    on_success: always
