sudo: false
language: node_js
node_js: 7
install:
  - npm install '@angular/cli' -g
  - npm install
  - gem install compass
script:
  - npm config ls -l
  - echo $TRAVIS_BRANCH
  - node --version
  - ng version
  - SCRIPTS_FN=src/environments/environment.prod.ts
  - sed "s/WENFO_GOOGLE_MAPS_API_KEY/$GOOGLE_MAPS_API_KEY/g" < $SCRIPTS_FN > tmp
  - mv tmp $SCRIPTS_FN
  - env BRANCH=$TRAVIS_BRANCH npm run build
deploy:
  # deploy to "wenfo.org/afms/staging" on branch master
  - skip_cleanup: true
    provider: script
    script: bash -c "cd dist && find . -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp.wenfo.org/staging/{} \;"
    on:
      branch: master
  # deploy to "wenfo.org/afms" on branch production
  - skip_cleanup: true
    provider: script
    script: bash -c "cd dist && find . -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp.wenfo.org{} \;"
    on:
      branch: production
notifications:
  email: false
  slack:
    rooms: wenfo:N1YfzQWaJ8wfjvrYarrh33PZ
    on_success: always
